---
title       : Predicting Usefulness of Yelp Reviews
subtitle    :
author      : Jim Curro, Eric Hare, Alex Shum
job         : Apr. 29, 2013
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

```{r setup, echo=FALSE, message=FALSE}
    ## Libraries
    library(rjson)
    library(plyr)
    library(maps)
    library(tm)
    library(ggplot2)
    library(xtable)
    library(e1071)
    library(randomForest)
```

## Introduction

```{r process, echo=FALSE, cache=TRUE}
    processData <- function(json) {
        lines <- readLines(json)
        json.lines <- lapply(1:length(lines), function(x) { fromJSON(lines[x])})
    }
    
    ## Read in json training files
    business.json <- processData("yelp_training_set_business.json")
    checkin.json <- processData("yelp_training_set_checkin.json")
    reviews.json <- processData("yelp_training_set_review.json")
    user.json <- processData("yelp_training_set_user.json")
    
    
    ## Reviews Data
    ## Convert to DF
    reviews.data <- data.frame(matrix(unlist(reviews.json), nrow = length(reviews.json), byrow = TRUE))
    names(reviews.data) <- c("funny", "useful", "cool", names(reviews.json[[1]])[-1])
    ## Fix some of the data types
    reviews.data$useful <- as.numeric(as.character(reviews.data$useful))
    reviews.data$cool <- as.numeric(as.character(reviews.data$cool))
    reviews.data$funny <- as.numeric(as.character(reviews.data$funny))
    
    
    ## Business Data
    ## We need to turn "Categories" into a comma separated string
    for (i in 1:length(business.json)) {
        business.json[[i]]$categories <- paste(business.json[[i]]$categories, collapse = ",")
    }
    business.data.tmp <- data.frame(matrix(unlist(business.json), nrow = length(business.json), byrow = TRUE))
    names(business.data.tmp) <- names(business.json[[1]])[-8]
    
    
    ## Checkin Data
    ##
    for (i in 1:length(checkin.json)) {
        checkins <- sum(unlist(checkin.json[[i]][-(c(length(checkin.json[[i]]), length(checkin.json[[i]]) - 1))]))
        business_id <- checkin.json[[i]]$business_id
        
        checkin.json[[i]] <- list(business_id = business_id, checkins = checkins)
    }
    checkin.data <- data.frame(matrix(unlist(checkin.json), nrow = length(checkin.json), byrow = TRUE))
    names(checkin.data) <- names(checkin.json[[1]])
    
    
    ## User Data
    user.data <- data.frame(matrix(unlist(user.json), nrow = length(user.json), byrow = TRUE))
    names(user.data) <- c("funny", "useful", "cool", names(user.json[[1]])[-1])
    user.data$useful <- as.numeric(as.character(user.data$useful))
    user.data$cool <- as.numeric(as.character(user.data$cool))
    user.data$funny <- as.numeric(as.character(user.data$funny))
    user.data$average_stars <- as.numeric(as.character(user.data$average_stars))
    user.data$review_count <- as.numeric(as.character(user.data$review_count))
    
    ####
    ## Merge Data
    ## Three sets, businesses and users, with reviews linking businesses to users
    ####
    business.data <- merge(business.data.tmp, checkin.data, by = "business_id")
    business.data$checkins <- as.numeric(as.character(business.data$checkins))
    business.data$review_count <- as.numeric(as.character(business.data$review_count))
    business.data$longitude <- as.numeric(as.character(business.data$longitude))
    business.data$stars <- as.numeric(as.character(business.data$stars))
    business.data$stars.f <- factor(business.data$stars)
    business.data$latitude <- as.numeric(as.character(business.data$latitude))
    
    ## Make sure all the reviews are text
    reviews.data$text <- as.character(reviews.data$text)

    ## Sample 20000 reviews so that the text processing will finish
    set.seed(20130421)
    data.sample <- sample(1:nrow(reviews.data), 20000)
    reviews.sub <- reviews.data[data.sample, ]

    ## Clean out the json files to save memory
    rm(reviews.json)
    rm(user.json)
    rm(business.json)
    rm(checkin.json)
    rm(reviews.data)
```

---

## Data: Businesses
```{r datapeek1}
    head(business.data, n = 1)
```

---

## Data: Users
```{r datapeek2}
    head(user.data, n = 1)
```

---

## Data: Reviews
```{r datapeek3}
    reviews.sub[18,]
```

---

## Data Analysis
...

---

## Useful vs Funny/Cool
```{r usefulvfunny, echo=FALSE}
    qplot(cool, useful, data = user.data, colour = I("blue")) + 
        geom_point(aes(x = funny, y = useful), colour = I("red")) +
        xlab("Cool/Funny Votes") +
        ylab("Useful Votes")
```

---

## City Data
```{r citydata, echo=FALSE, results='asis'}
    business.data$full_address <- as.character(business.data$full_address)
    
    business.data$zip <- substring(business.data$full_address, nchar(business.data$full_address) - 5, nchar(business.data$full_address))
    
    city.data = ddply(business.data,.(city),summarize,
      reviews = sum(review_count),
      checkins = sum(checkins))
    
    city.data <- city.data[with(city.data, order(-checkins)), ]
    
    city.data$percentage <- city.data$reviews/city.data$checkins
    
    print(xtable(city.data[1:10,], label = "tab:CityData", caption = "Top ten cities by the number of checkins in that city"), include.rownames = FALSE, type = "html")
```

---

## Checkins
```{r checkins, echo=FALSE}
    qplot(stars.f, log(checkins), data = business.data, geom = "boxplot", colour = stars.f) +
        xlab("Average star rating") +
        ylab("Number of checkins")
```

---

## Useful Users
```{r usefulusers, echo=FALSE, results='asis'}
    use = subset(user.data,review_count>100)
    use$good = use$useful / use$review
    use = use[with(use,order(-good)),]
    
    print(xtable(use[1:10, c(1:3, 5:7, 9)], caption = "Top ten users in the Yelp data by total number of useful votes per review (Minimum 100 reviews).", label = "tab:UsefulTable"), include.rownames = FALSE, type = "html")
```

---

## Usefulness by Star Rating
```{r usefulbystars, echo=FALSE}
    user.data$frc = '<50'
    user.data$frc[user.data$review_count > 50] = '50-200'
    user.data$frc[user.data$review_count > 200] = '200-500'
    user.data$frc[user.data$review_count > 500] = '500-1000'
    user.data$frc[user.data$review_count > 1000] = '>1000'

    qplot(data=user.data,average_stars,useful,color = frc) +
        xlab("Average star rating") +
        ylab("Number of useful reviews")
```

## Preprocessing and Classification

---

## R Memory and Computation Time Issues

---

## Classification

---

```{r loaduseful, echo=FALSE}
    ## Generate summary statistics
    reviews.sub$numChar <- sapply(reviews.sub$text, nchar)
    reviews.sub$numCap <- sapply(reviews.sub$text, function(x) { length(grep("[A-Z]", strsplit(as.character(x), split = "")[[1]])) / (nchar(x) + 1)})
    reviews.sub$numPunc <- sapply(reviews.sub$text, function(x) { length(grep("[^a-zA-Z ]", strsplit(as.character(x), split = "")[[1]])) / (nchar(x) + 1)})
    reviews.sub$numPar <- sapply(reviews.sub$text, function(x) { length(grep("\n", strsplit(as.character(x), split = "")[[1]])) / (nchar(x) + 1)})
    
    # Load important words
    important.words <- read.csv("m.csv")

    reviews.final <- merge(reviews.sub, user.data[,c("user_id", "average_stars", "useful", "review_count")], by = "user_id", all.x = TRUE, suffixes = c(".review", ".user"))

    reviews.final$useful.user[is.na(reviews.final$useful.user)] <- 0
    reviews.final$review_count[is.na(reviews.final$review_count)] <- 0
    reviews.final$average_stars[is.na(reviews.final$average_stars)] <- 0

    reviews.final$useful.per <- reviews.final$useful.user / (reviews.final$review_count + 1)
    
    reviews.final$useful_bin <- reviews.final$useful.review > 0
    summary.sub <- ddply(reviews.final, .(useful_bin), summarise, numChar = mean(numChar), numCap = mean(numCap), numPunc = mean(numPunc), numPar = mean(numPar), useful.per = mean(useful.per), average_stars = mean(average_stars))

```


## Characteristics of Useful Reviews
```{r usefulrevs, echo=FALSE, results='asis'}
    print(xtable(summary.sub, label = "tab:SummaryTable", caption = "Summary statistics for all reviews by whether the review was voted as useful or not.  The variables include the number of characters, percentage of letters capitalized, percentage of letters that are punctuation characters, paragraphs per length of review, the number of useful votes for the particular user writing the review over the total number of reviews for that user, and the average star rating of the business being reviewed.", digits = 4), table.placement = 'H', type = "html")
```

---

```{r themodel, echo=FALSE, cache=TRUE}
    classError <- function(table) {
        cls1 <- (table[1,2] / (table[1,2] + table[1,1]))
        cls2 <- (table[2,1] / (table[2,2] + table[2,1]))
        
        return(list(overall = mean(c(cls1, cls2)), usefulError = cls2, notusefulError = cls1))
    }

    reviews.train <- reviews.final[1:18000, ]
    reviews.test <- reviews.final[18001:20000,]
    reviews.test <- reviews.test[complete.cases(reviews.test),]
    reviews.test.truth <- reviews.test$useful_bin

    reviews.rf <- randomForest(factor(useful_bin) ~ stars+numChar+numCap+numPunc+numPar+useful.per+average_stars, data = reviews.train, importance = TRUE, ntree = 1000)

    reviews.svm <- svm(factor(useful_bin) ~ numChar+numPar+numPunc+numCap+useful.per+average_stars, data = reviews.train, kernel = "linear")

    predict.svm <- predict(reviews.svm, reviews.test)
```

## Random Forest Importance
```{r rfimp, echo=FALSE, results='asis'}
    print(xtable(reviews.rf$importance, label = "tab:RandomForest", caption = "A list of the variables and their importance as determined by the randomForest algorithm.  We ultimately selected six of these variables, numChar, numPar, numCap, and numPunc, useful.per, and average stars for use in our SVM.", digits = 4), table.placement = 'H', type = "html")
```

---

## Our Final SVM

---

## Truth Table
```{r truthtab, echo=FALSE, results='asis'}
    tbl <- table(predict.svm, reviews.test.truth)

    print(xtable(tbl, label = "tab:SVM", caption = "Truth Table for the results of our model"), table.placement = 'H', type = "html")
```

---

## Results
```{r results, echo=FALSE, results='asis'}
    print(xtable(data.frame(Type = c("Useful Error", "Not Useful Error", "Overall Error"), ErrorRates = c(classError(tbl)$usefulError, classError(tbl)$notusefulError, classError(tbl)$overall)), label = "tab:ClassErrorTable", caption = "Individual and overall class error rates for our model", digits = 4), table.placement = 'H', type = "html")

```

---